# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5a02e6b699d9bd20347f40b5e4e496f5dc1705c63d7871986cb76e01b8f7d950f48607a308013bdeb6680a9f9cb29e21044824ce9fc1769193682268020e057

test:
  secret_key_base: 374dd910e29dc471c1ecb8d194e872f36b58a58407e0a17a49596225a3b50d2e23324980963398295873f53c594178d9f4296642dbcb8900a7865c9aa3815ffc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
